modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="dannys_expansion"
version="${file.jarVersion}"
displayName="Danny's Expansion"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="My mom."
authors="BottomTextDanny, Yosh" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Fantasy-oriented mod about progression.
'''
[[dependencies.dannys_expansion]]
    modId="braincell"
    mandatory=true
    versionRange="[1.05,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dannys_expansion]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dannys_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
